- project:
    name: openstack/puppet-barbican
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-scenario002
      - puppet-openstack-beaker-jobs
